### ISSUE TITLE
[ REFACTOR ] 커뮤니티 응답 방식 수정

### ISSUE THREAD

**Issue by yunhacandy** [IT-Cotato/9th-Growing-Pain-BE#115]
# 🛠️ Description for refactoring features
커뮤니티 응답 방식 수정

## 📝 Todo-lists
- [x] 게시글 좋아요 누를 때 응답형식 수정
- [x] 댓글 좋아요 누를 때 응답형식 수정
- [x] 답글 좋아요 누를 때 응답형식 수정
