### ISSUE TITLE
[ REFACTOR ] 커뮤니티 관련 기능 수정

### ISSUE THREAD

**Issue by yunhacandy** [IT-Cotato/9th-Growing-Pain-BE#117]
# 🛠️ Description for refactoring features
커뮤니티 관련 기능 수정

## 📝 Todo-lists
- [x] 댓글 조회 응답 형식 수정
- [x] 답글 조회 응답 형식 수정
- [x] 포스트 isDeleted이 true인건 목록에 반환되지 않게 에러 수정
- [x] 댓글도 isDeleted이 true인건 목록에 반환되지 않게 에러 수정
- [x] 답글도 isDeleted이 true인건 목록에 반환되지 않게 에러 수정
