### ISSUE TITLE
[ REFACTOR ] 커뮤니티 관련 기능 리팩토링

### ISSUE THREAD

**Issue by yunhacandy** [IT-Cotato/9th-Growing-Pain-BE#131]
# 🛠️ Description for refactoring features
커뮤니티 관련 기능을 전체적으로 리팩토링합니다.

## 📝 Todo-lists
- [x] 게시글 목록 요청에서 댓글 개수도 반환
- [x] 사용자가 좋아요 누른 댓글 반환
- [x] 게시글 이미지 여러개 가능하게
- [x] 사용자가 좋아요 누른 답글 반환
- [ ] 게시글 수정할때 다 안넣어도 되게..
- [x] 복구 기능 없으니까 그냥 delete되게?
