### ISSUE TITLE
[ REFACTOR ] 회원가입 관련 리팩토링

### ISSUE THREAD

**Issue by yunhacandy** [IT-Cotato/9th-Growing-Pain-BE#132]
# 🛠️ Description for refactoring features
리팩토링 작업할 사항에 대해 작성해주세요.

## 📝 Todo-lists
- [x] 회원가입, 로그인 분리
- [ ]  이메일 형식 아니면 경고문 나오게
- [ ]  비밀번호 형식 검증
- [ ]  token은 header로
