### ISSUE TITLE
[ BUG ] - MySQL connection / Table Mapping error

### ISSUE THREAD

**Issue by nar0ng** [IT-Cotato/9th-Growing-Pain-BE#21]
## 🛠️ Description for bug 
버그 관련 사항에 대해 작성해주세요.

### 어떤 버그인가요?

> 버그에 대해 알려주세요
- MySQL connection error 및 테이블 매핑 에러
<br><br>

### 어떤 상황에서 겪으셨나요?

> 버그를 겪으신 상황을 알려주세요
<img width="1264" alt="image" src="https://github.com/IT-Cotato/9th-Growing-Pain-BE/assets/71819594/203b264a-0ce0-4c77-bd0b-11b19698bee4">
<img width="1078" alt="image" src="https://github.com/IT-Cotato/9th-Growing-Pain-BE/assets/71819594/4d2175d0-d553-4434-9143-e021969e8479">

<br><br>
- Application Run Failed 

### 참고할만한 자료가 있을까요?

> 참고자료가 있다면 첨부해주세요

<br><br>
https://velog.io/@songsunkook/학과-조회-API
https://velog.io/@hellojihyoung/Spring-JoinColumn의-name과-referencedColumnName

## 📝 Todo-lists
- [x] ActivityLog, MemberJobApplication에서 @JoinColumn에 referenceColumnName 삭제
- [x] Member의 field, belong 수정
- [x] failed to to open the referenced table 'post' 오류
