### ISSUE TITLE
[ FEATURE ] Build CI/CD

### ISSUE THREAD

**Issue by yunhacandy** [IT-Cotato/9th-Growing-Pain-BE#8]
## 🛠️ Description for development features
![image](https://github.com/IT-Cotato/9th-Growing-Pain-BE/assets/127095481/17bd7af1-5896-4781-ac4c-342fb1343dc6)
프로젝트 자동 배포를 위한 CI/CD를 구축합니다.

## 📝 Todo-lists
- [x] AWS EC2 설정
- [x] AWS S3 설정
- [x] AWS CodeDeploy 설정
- [x] github actions 및 프로젝트 코드 설정
